added a link to the official Laravel blog
fbdevelopercircles/FbDevcCommunityContent pull request #197
Opened 2020-08-03 12:53 UTC by stephenjude

#### What does this PR do?
Shows the link to the official Laravel blog

2020-08-04 11:26 UTC, prilcool approved these changes
-Approved for merging  :)

2020-08-10 17:48 UTC, BolajiAyodeji requested changes
Please fix the conflicts and we'll get this merged.

2020-08-11 11:17 UTC, stephenjude commented
@BolajiAyodeji done

2020-08-12 16:54 UTC, stephenjude commented
@BolajiAyodeji you can now merge this pull request.

2025-05-20 10:01 UTC, closed without merging